### ISSUE TITLE
Missing words, round 2

### ISSUE THREAD

**Issue by okdana** [marcoagpinto/aoo-mozilla-en-dict#17] opened 2015-09-08 14:36 UTC
Hello, sorry to bother you again so soon. I've just returned to work today and checked my personal dictionary file here, and i discovered several terms that i missed in my last submission. I've provided my own citation links this time, hope that makes things easier for you.

I know there's sometimes an issue in spell-checking where obscure/niche words can cause problems for checking more common words. If that's a concern, i would recommend carefully reviewing *cron* (which might disrupt *corn*) and *daemonise* (which might disrupt *demonise*); all of the others seem safe.

## Contractions

* [that've](https://en.wiktionary.org/wiki/that've) — *that have*
* [there've](https://en.wiktionary.org/wiki/there've) — *there have*
* [which've](https://en.wiktionary.org/wiki/which've) — *which have*

## General

* [unsupportive](https://en.wiktionary.org/wiki/unsupportive) — not supportive

## Binary (2^n) data units

* [kibibit/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [mebibit/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [gibibit/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [tebibit/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [pebibit/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [exbibit/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [zebibit/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [yobibit/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [kibibyte/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [mebibyte/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [gibibyte/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [tebibyte/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [pebibyte/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [exbibyte/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [zebibyte/S](https://en.wikipedia.org/wiki/Binary_prefix)
* [yobibyte/S](https://en.wikipedia.org/wiki/Binary_prefix)

## Computing

* [anonymiser/S](https://en.wikipedia.org/wiki/Anonymizer)
  — something which anonymises (i.e., a proxy)
* [backtrace/DGS](https://en.wikipedia.org/wiki/Stack_trace)
  — stack trace (not sure why there's a space in *stack trace* but not
    *backtrace*, but that seems to be the prevailing usage)
* [bashism/S](https://en.wiktionary.org/wiki/bashism)
  — non-portable shell feature
* [bi-endian](https://en.wikipedia.org/wiki/Endianness)
  — word byte order
* [big-endian](https://en.wikipedia.org/wiki/Endianness)
  — word byte order
* [bytecode](https://en.wikipedia.org/wiki/Bytecode)
  — intermediate code instruction set
* [callable/S](http://php.net/manual/en/language.types.callable.php)
  — function/object which can be called, in many programming languages
    (both a noun and an adjective)
* [classful](https://en.wikipedia.org/wiki/Classful_network)
  — having or recognising classes (opposite of *classless*)
* [cron](https://en.wikipedia.org/wiki/Cron)
  — UNIX job scheduler
  (sometimes used as an acronym or proper noun, but usually just a common noun)
* [draggability](https://en.wiktionary.org/wiki/draggability)
  — capability of a user-interface component to be dragged
* [draggable](https://en.wiktionary.org/wiki/draggability)
  — something which has draggability
* [daemonise/DG](https://en.wiktionary.org/wiki/daemonize)
  — to run a process as a daemon
    (not to be confused with *demonise*)
* [diff/DGS](https://en.wikipedia.org/wiki/Diff_utility)
  — difference set or patch (both a noun and a verb)
* [endian/P](https://en.wikipedia.org/wiki/Endianness)
  — word byte order
* [idempotence](https://en.wikipedia.org/wiki/Idempotence)
  — quality of being idempotent
* [little-endian](https://en.wikipedia.org/wiki/Endianness)
  — word byte order
* [metasyntactic](https://en.wikipedia.org/wiki/Metasyntactic_variable)
  — part of *metasyntactic variable*, a place-holder variable name used in
    documentation and examples (such as `foo`, `bar`, and `baz` in English)
* [nullable](https://en.wikipedia.org/wiki/Nullable_type)
  — able to be null, in many programming languages
    (might also be a noun like *callable*?)
* [opcode](https://en.wikipedia.org/wiki/Opcode)
  — processor/interpreter instruction
* [pageable](https://en.wikipedia.org/wiki/Paging)
  — capable of memory paging (consider also *non-pageable*?)
* [parallelise/DGN](https://en.wiktionary.org/wiki/parallelize#English)
  — to make parallel (verb),
    the process of making something parallel (noun)
* [performant](https://en.wiktionary.org/wiki/performant)
  — exhibiting high efficiency/performance
* [proxy/DG](https://en.wikipedia.org/wiki/Proxy_server)
  — to pass through a proxy (verb)
* [stateful](https://en.wikipedia.org/wiki/Stateful_firewall)
  — having or recognising states (opposite of *stateless*, often used in the
    context of firewalls)
* [template/DG](https://en.wikipedia.org/wiki/Template_processor)
  — noun and verb describing the use of templates
* [tokenisation](https://en.wikipedia.org/wiki/Tokenization_%28lexical_analysis%29)
  — process of breaking text up into meaningful components
* [tokeniser/S](https://en.wikipedia.org/wiki/Tokenization_%28lexical_analysis%29)
  — something which performs tokenisation

**Comment by marcoagpinto** [comment] 2015-09-09 10:36
Hello,

I believe to have added all except two:
1. callables (wasn't able to find the plural in dictionaries)
2. non-pageable (the problem is that "non" sometimes is followed by an hyphen or not, and I couldn't find it in the dictionaries)

Dana, before adding words to en_GB I first search for them in 1) Oxford and 2) Collins.

As a last resource I search in Wiktionary and the last, last, last resource, Wikipedia.

I use Wikipedia more to find person/places names and to check if they have a 's.

Thanks!

Here are the words I added today:
9-SEP-2015
7793) miscreate (+s +ing +ed)
7794) miscreative
7795) Germain (+'s - name - Wikipedia)
7796) that've (Wiktionary)
7797) there've (Wiktionary)
7798) which've (Wiktionary)
7799) unsupportive
8800) kibibit (+plural - IEC - Wikipedia)
8801) mebibit (+plural - IEC - Wikipedia)
8802) gibibit (+plural - IEC - Wikipedia)
8803) tebibit (+plural - IEC - Wikipedia)
8804) pebibit (+plural - IEC - Wikipedia)
8805) exbibit (+plural - IEC - Wikipedia)
8806) zebibit (+plural - IEC - Wikipedia)
8807) yobibit (+plural - IEC - Wikipedia)
8808) kibibyte (+plural - IEC - Wikipedia)
8809) mebibyte (+plural - IEC - Wikipedia)
8810) gibibyte (+plural - IEC - Wikipedia)
8811) tebibyte (+plural - IEC - Wikipedia)
8812) pebibyte (+plural - IEC - Wikipedia)
8813) exbibyte (+plural - IEC - Wikipedia)
8814) zebibyte (+plural - IEC - Wikipedia)
8815) yobibyte (+plural - IEC - Wikipedia)
8816) anonymiser (+plural - Wiktionary)
8817) backtrace (+s +ing +ed - Wiktionary)
8818) bashism (+plural - Wiktionary)
8819) bi-endian (Wiktionary)
8820) big-endian
8821) little-endian
8822) bytecode (+plural - Wiktionary)
8823) misprice (+s +ing +ed)
8824) noncallable
8825) classful (Wiktionary)
8826) cron
8827) draggability (Wiktionary)
8828) draggable (Wiktionary)
8829) daemonize (+s +ing +ed - Wiktionary)
8830) diff (+s +ing +ed)
8831) endian
8832) idempotence
8833) ‎idempotency
8834) metasyntactic (Wiktionary)
8835) nullable
8836) opcode (+plural)
8837) pageable (Wiktionary)
8838) parallelize (+s +ing +ed +ion -IZE)
8839) parallelise (+s +ing +ed +ion -ISE)
8840) performant (Wiktionary)
8841) procuracy (+plural)
8842) proxying + proxied (merged into proxy - Wiktionary)
8843) stateful
8844) Marston (+'s - name - Wikipedia)
8845) bedplate
8846) templating + templated (Wiktionary)
8847) tokenisation (Wiktionary)
8848) tokeniser (+plural - Wiktionary)

**Closed by marcoagpinto** 2015-09-09 10:36 UTC

**Comment by okdana** [comment] 2015-09-09 21:15
Thanks again
